### ISSUE TITLE
TypeError: Cannot read property 'localeCompare' of undefined

### ISSUE THREAD

**Issue by TwistMeister** [netlify-labs/netlify-cms-widget-parent#259]
**Describe the bug**
Clicking on the Parent widgets select box results in an error.

**To Reproduce**
Add a new entry for a collection and then try to change the desired parent by clicking the widgets instance, a select box.

**Expected behavior**
The select box should show a list with available folders to set as a parent for the entry we are creating. Possibly mimicking the tree structure you also have in the left navigation pane. And probably leaving out collections that have a setting for `create: false`.

**Applicable Versions:**
 - Netlify CMS version: `netlify-cms@2.10.139`
 - Git provider: `proxy`
 - Browser version: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36`

**Comment by erezrokah** [comment]
Hi @TwistMeister, this widget is highly experimental and only works under very specific conditions.

I suggest you start with the example https://github.com/netlify-labs/netlify-cms-widget-parent/tree/main/example and then modify it to your needs to figure out what's not working.

Also sharing a public repo with a reproduction will help.

**Comment by erezrokah** [comment]
Closing as stale
